<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="LegalNormRules" nsURI="http://www.example.org/LegalNormRules"
    nsPrefix="LegalNormRules">
  <eClassifiers xsi:type="ecore:EClass" name="LegalConsequence" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="legalobligation" lowerBound="1"
        upperBound="-1" eType="#//LegalObligation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prerequisit" lowerBound="1"
        eType="#//Prerequisit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LegalObligation" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="LegalNormRules" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="legalconsequence" lowerBound="1"
        upperBound="-1" eType="#//LegalConsequence" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Connector" abstract="true" interface="true"
      eSuperTypes="#//Prerequisit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="prerequisit" lowerBound="1"
        upperBound="2" eType="#//Prerequisit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//ContextPrerequisit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presumedState" lowerBound="1"
        eType="ecore:EClass ../../mdpa.gdpr.metamodel/model/GDPR.ecore#//AbstractGDPRElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextDependentProperty" eSuperTypes="#//ContextPrerequisit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="propertyValue" lowerBound="1"
        eType="ecore:EClass ../../mdpa.gdpr.metamodel.contextproperties/model/contextproperties.ecore#//PropertyValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NOT" eSuperTypes="#//Prerequisit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="negatedPrerequisit" lowerBound="1"
        eType="#//Prerequisit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AND" eSuperTypes="#//Connector"/>
  <eClassifiers xsi:type="ecore:EClass" name="OR" eSuperTypes="#//Connector"/>
  <eClassifiers xsi:type="ecore:EClass" name="Prerequisit" abstract="true" interface="true"
      eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="PresumedGDPRElementProvider" eSuperTypes="../../tools.mdsd.modelingfoundations.identifier/model/identifier.ecore#//Entity">
    <eStructuralFeatures xsi:type="ecore:EReference" name="presumedGDPRElement" upperBound="-1"
        eType="ecore:EClass ../../mdpa.gdpr.metamodel/model/GDPR.ecore#//AbstractGDPRElement"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextPrerequisit" abstract="true"
      interface="true" eSuperTypes="#//Prerequisit">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceElement" lowerBound="1"
        eType="ecore:EClass ../../mdpa.gdpr.metamodel/model/GDPR.ecore#//AbstractGDPRElement"/>
  </eClassifiers>
</ecore:EPackage>
