#

pluginName = mdpa.lnr.metamodel Edit Support
providerName = www.example.org

_UI_CreateChild_text = {0}
_UI_CreateChild_text2 = {1} {0}
_UI_CreateChild_text3 = {1}
_UI_CreateChild_tooltip = Create New {0} Under {1} Feature
_UI_CreateChild_description = Create a new child of type {0} for the {1} feature of the selected {2}.
_UI_CreateSibling_description = Create a new sibling of type {0} for the selected {2}, under the {1} feature of their parent.

_UI_PropertyDescriptor_description = The {0} of the {1}

_UI_LegalConsequence_type = Legal Consequence
_UI_Prerequisit_type = Prerequisit
_UI_LegalObligation_type = Legal Obligation
_UI_Connector_type = Connector
_UI_Attribute_type = Attribute
_UI_ContextDependentProperty_type = Context Dependent Property
_UI_NOT_type = NOT
_UI_AND_type = AND
_UI_OR_type = OR
_UI_LegalNormRules_type = Legal Norm Rules
_UI_Unknown_type = Object

_UI_Unknown_datatype= Value

_UI_LegalConsequence_legalobligation_feature = Legalobligation
_UI_LegalConsequence_prerequisit_feature = Prerequisit
_UI_Connector_prerequisit_feature = Prerequisit
_UI_LegalNormRules_legalconsequence_feature = Legalconsequence
_UI_Unknown_feature = Unspecified

